import type { NextPage } from 'next';
import Head from 'next/head';
import { configureStore } from '@reduxjs/toolkit';
import { pokemonsSlice } from '../features/pokemons';
import { Provider } from 'react-redux';
import { PokemonList } from '../components/PokemonList';

const store = configureStore({
  reducer: pokemonsSlice.reducer,
});

const Home: NextPage = () => {
  return (
    <Provider store={store}>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin=""
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap"
            rel="stylesheet"
          />
        </Head>

        <main className="flex flex-col items-center py-20">
          <h1 className="mb-8 text-4xl">Welcome to the World of Pokemon</h1>
          <PokemonList />
        </main>
      </div>
    </Provider>
  );
};

export default Home;
